spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/database
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create